# Generated by Django 5.0.8 on 2024-11-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0004_basketproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
