# Generated by Django 5.0.8 on 2024-11-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0007_favoriler_yorumlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorumlar',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='yorumlar',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
